### ISSUE TITLE
Refactor `WebUser` - Breaking Changes

### ISSUE THREAD

**Issue by aurelticot** [verida/verida-js#336]
Most the following is introducing BREAKING CHANGES!

```[tasklist]
### Tasks
- [x] Move client instance creation in constructor so property is never undefined
- [x] Create dedicated auto connect method if has sessions (to avoid `isConnect` to be a Promise)
- [x] Check `context`, `account` and `did` instance property in `isConnect`
- [x] Remove returning Promises when not needed
- [x] Fix `WebUserProfile.avatarUri` not undefined in interface definition while it can be
- [x] Optimise imports with `import type`
- [x] Simplify TypeScript syntax
```

The main (breaking) change is about functions returning Promises while it's not needed, which is a bit annoying at usage.

`getDid`, `getContext`, `getAccount` were returning Promises because of `requireConnection` being async, because of `isConnected` being async, because of the auto-connnect.
By removing the auto-connect from `isConnected`, moving it into a dedicated function, we remove all the subsequent Promises.

`getClient` returned a Promise for no reasons.
